name: WineHQ Installation
on: [workflow_dispatch]

jobs:
  install-wine:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install WineHQ (Ubuntu 24.04 workaround)
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -p /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg
          echo "deb [arch=amd64,i386 signed-by=/etc/apt/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/winehq-jammy.list
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable

      - name: Initialize Wine
        run: |
          wine wineboot --init
          sleep 5

      - name: Capture ALL Wine files
        run: |
          mkdir -p wine-dist
          cp $(which wine) wine-dist/
          cp $(which wineserver) wine-dist/
          cp -r /usr/lib/i386-linux-gnu/wine wine-dist/lib32
          cp -r /usr/lib/x86_64-linux-gnu/wine wine-dist/lib64
          cp -r ~/.wine wine-dist/config
          tree wine-dist -L 2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-full-dist
          path: wine-dist/
          retention-days: 1
