name: WineHQ Build and Deploy
on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install WineHQ
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -p /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg
          echo "deb [arch=amd64,i386 signed-by=/etc/apt/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/winehq-jammy.list
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable wine32

      - name: Prepare Wine Files
        run: |
          mkdir -p wine-build
          
          cp $(which wine) wine-build/
          cp $(which wineserver) wine-build/
          
          mkdir -p wine-build/lib
          ldd $(which wine) | awk '/=>/ {print $3}' | xargs -I {} cp -L {} wine-build/lib/
          
          mkdir -p wine-build/config
          WINEPREFIX=./wine-build/config winecfg &>/dev/null & sleep 10

      - name: Commit and Push to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          mkdir -p dist/wine
          cp -r wine-build/* dist/wine/
          
          git add dist/
          git commit -m "Update WineHQ build $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:$GITHUB_REF
