name: Install WineHQ on Ubuntu 24.04
on:
  workflow_dispatch:

jobs:
  install-wine:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Enable 32-bit architecture
        run: sudo dpkg --add-architecture i386

      - name: Add WineHQ repository (Ubuntu 22.04/Jammy)
        run: |
          sudo mkdir -p /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg
          echo "deb [arch=amd64,i386 signed-by=/etc/apt/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/winehq-jammy.list

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable

      - name: Verify installation
        run: wine --version

      - name: Prepare Wine files
        run: |
          mkdir -p WineHQ
          cp -r ~/.wine WineHQ/
          cp $(which wine) WineHQ/

      - name: Push to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add WineHQ/
          git commit -m "Add WineHQ binaries"
          git push origin HEAD:main
