name: WineHQ Complete Capture
on: [workflow_dispatch]

jobs:
  capture-wine:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install WineHQ
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -p /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg
          echo "deb [arch=amd64,i386 signed-by=/etc/apt/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/winehq-jammy.list
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable wine32

      - name: Initialize Wine
        run: |
          mkdir -p ~/.wine
          WINEPREFIX=~/.wine winecfg

      - name: Capture Wine Distribution
        run: |
          mkdir -p wine-dist
          
          cp $(which wine) wine-dist/
          cp $(which wineserver) wine-dist/
          
          mkdir -p wine-dist/lib
          ldd $(which wine) | awk '/=>/ {print $3}' | xargs -I {} cp -L {} wine-dist/lib/
          
          mkdir -p wine-dist/lib32
          ldd $(which wine) | grep -i 32 | awk '/=>/ {print $3}' | xargs -I {} cp -L {} wine-dist/lib32/
          
          mkdir -p wine-dist/config
          cp -r ~/.wine/drive_c wine-dist/config/
          cp -r ~/.wine/system.reg wine-dist/config/
          cp -r ~/.wine/user.reg wine-dist/config/
          cp -r ~/.wine/userdef.reg wine-dist/config/

          tree wine-dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-complete
          path: wine-dist/
