name: WineHQ Installation
on:
  workflow_dispatch:

jobs:
  install-wine:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up WineHQ (Ubuntu 24.04 workaround)
        run: |
          # Enable 32-bit architecture
          sudo dpkg --add-architecture i386
          
          # Add WineHQ repository (using Jammy for compatibility)
          sudo mkdir -p /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg
          echo "deb [arch=amd64,i386 signed-by=/etc/apt/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/winehq-jammy.list
          
          # Install Wine with recommended dependencies
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable

      - name: Initialize Wine environment
        run: |
          # Explicitly create Wine prefix
          wine wineboot --init
          sleep 10  # Wait for initialization

      - name: Prepare Wine files
        run: |
          mkdir -p WineHQ
          
          # Copy essential files (include both binaries and config)
          cp -r "$(which wine)" WineHQ/
          cp -r "$HOME/.wine" WineHQ/ || echo ".wine not found, continuing without config"
          
          # Verify structure
          ls -la WineHQ/

      - name: Push to repository
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add WineHQ/
          git commit -m "Add WineHQ files - $(date)"
          git push origin HEAD:main
